### ISSUE TITLE
Migrate from jcenter

### ISSUE THREAD

**Issue by mochadwi** [pedroql/mvflow#37]
https://jeroenmols.com/blog/2021/02/04/migratingjcenter/#published-artifacts-to-bintrayjcenter

**Comment by pedroql** [comment]
As of [1.0.2](https://github.com/pedroql/mvflow/releases/tag/v1.0.2) this library should be hosted on maven central. 1.0.2 is the same as 1.0.1 otherwise so all you need to do is bumping the version and ensure you have maven central in your repositories (which you probably already do).
